GRANT select, insert ON nitroxy_retail.account TO 'nitroxy_retail'@'localhost';
GRANT select, insert ON nitroxy_retail.account_transaction TO 'nitroxy_retail'@'localhost';
GRANT select, insert ON nitroxy_retail.account_transaction_contents TO 'nitroxy_retail'@'localhost';
GRANT select, insert, update, delete ON nitroxy_retail.categories TO 'nitroxy_retail'@'localhost';
GRANT select, insert ON nitroxy_retail.deliveries TO 'nitroxy_retail'@'localhost';
GRANT select, insert ON nitroxy_retail.delivery_contents TO 'nitroxy_retail'@'localhost';
GRANT select, insert ON nitroxy_retail.product_log TO 'nitroxy_retail'@'localhost';
GRANT select, insert ON nitroxy_retail.product_package TO 'nitroxy_retail'@'localhost';
GRANT select, insert, update ON nitroxy_retail.products TO 'nitroxy_retail'@'localhost';
GRANT select, insert ON nitroxy_retail.transaction_contents TO 'nitroxy_retail'@'localhost';
GRANT select, insert ON nitroxy_retail.transactions TO 'nitroxy_retail'@'localhost';
GRANT select, insert, update ON nitroxy_retail.users TO 'nitroxy_retail'@'localhost';
GRANT select, insert ON nitroxy_retail.daily_count TO 'nitroxy_retail'@'localhost';
